[package]
name = "rusty-grep"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0.0"
colored = "2"
clap = { version = "3.0.10", features = ["derive"] }
